# -*- coding: utf-8 -*-
"""Ai compute case study .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1QIng4uSTUfjM7d6dCOo8SDV6Ncr_Q5
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# !pip install pyspark

from pyspark.sql import SparkSession

"""#Q1. Spark Initialization and Data Loading"""

spark = SparkSession.builder.appName("SmartTransportationAnalytics").getOrCreate()

sc = spark.sparkContext

df_lowercase = spark.read.csv("1traffic.csv", header=True, inferSchema=True)

#Schema for traffic.csv
df_lowercase.printSchema()

#Sample Records for traffic.csv
df_lowercase.show(5)

df_uppercase = spark.read.csv("Traffic.csv", header=True, inferSchema=True)

#Schema for Traffic.csv
df_uppercase.printSchema()

#Sample Records for Traffic.csv
df_uppercase.show(5)

"""#Q2. RDD Implementation"""

#create RDD
rdd_traffic = df_lowercase.rdd
rdd_Traffic = df_uppercase.rdd

#Analyzing traffic.csv (Junctions with high vehicle count)
#Transformation 1: Filter rows where Vehicles > 50
filtered_rdd = rdd_traffic.filter(lambda row: row["Vehicles"] > 50)

"""keeinp the hours where the sensor counted more than 50 vehicles to find the times when there is actual traffic congestion"""

for row in filtered_rdd.take(5):
    print(row)

#Transformation 2: Map to (Junction, Vehicles) pairs
mapped_rdd = filtered_rdd.map(lambda row: (row["Junction"], row["Vehicles"]))

"""filtering out all the unnecessary columns and reorganisinf the data into clean pairs"""

for row in mapped_rdd.take(5):
    print(row)

# Action 1: Take the first 5 records
print("Sample High-Traffic Records (Junction, Vehicles):\n", mapped_rdd.take(5))

"""At Junction 1, there was an hour where the sensor recorded exactly 70 vehicles, etc"""

#Analyzing Traffic.csv (Total Vehicles by Traffic Situation)
# Transformation 1: Map to (Traffic Situation, Total Count) pairs
situation_pairs = rdd_Traffic.map(lambda row: (row["Traffic Situation"], row["Total"]))

# Action 2: ReduceByKey to aggregate total vehicles per traffic situation
aggregated_rdd = situation_pairs.reduceByKey(lambda a, b: a + b)

"""groups all the pairs that share the exact same text key, and adds their totals together"""

#Aggregated Traffic Situation Counts
for situation, total_count in aggregated_rdd.collect():
    print(f"Situation: {situation} -> Total Vehicles: {total_count}")

"""total of all vehicles tracked, broken down by the traffic situation category.

#Q3. Key-Value Operations and Persistence
"""

from pyspark import StorageLevel

#Key-Value Operations & Shuffle
# 1. Create a Key-Value RDD (Junction, Vehicles) from traffic.csv
kv_rdd = rdd_traffic.map(lambda row: (row["Junction"], row["Vehicles"]))

"""selecting the "junction" and the "vehicle" column"""

# 2. Shuffle Operation: Aggregate total vehicles by Junction using reduceByKey
shuffled_rdd = kv_rdd.reduceByKey(lambda a, b: a + b)

"""shuffling and grouping all records with the same key together."""

#Demonstrating RDD Persistence
# 3. Persist the shuffled RDD in memory to optimize future actions
shuffled_rdd.persist(StorageLevel.MEMORY_ONLY)

"""saving the result directly in the computer's RAM (memory)"""

# Action 1: Trigger computation and cache the data
print("Total Vehicles by Junction (First Action):")
for junction, total in shuffled_rdd.collect():
    print(f"Junction {junction}: {total} vehicles")

# Action 2: Fast retrieval from memory cache
print("\nCounting number of unique junctions (Second Action from Cache):")
print(f"Total Unique Junctions: {shuffled_rdd.count()}")

"""grabing the pre-calculated results straight out of the memory cach"""

# 4. Unpersist to free up memory resources
shuffled_rdd.unpersist()

"""#Q4. Spark DataFrame Operations"""

from pyspark.sql import functions as F

"""1. Selection & Filtering"""

# Select specific columns and filter for high car counts in df_uppercase
filtered_df = df_uppercase.select("Date", "Day of the week", "CarCount", "Traffic Situation").filter(df_uppercase["CarCount"] > 100)
filtered_df.show(5)

"""choosing the "heavy" Traffic Situation i.e the congestions times

2. Grouping & Aggregation
"""

# Group by Traffic Situation to find average vehicle components
agg_df = df_uppercase.groupBy("Traffic Situation").agg(
        F.avg("CarCount").alias("Avg_Cars"),
        F.avg("BikeCount").alias("Avg_Bikes"),
        F.max("Total").alias("Max_Total_Vehicles")
    )
agg_df.show()

"""calculating the average number of vehicles max total vehicels fpr each traffic situation

3. Join Operation
"""

# To perform a join, we prepare a common key (Date) in both DataFrames
# Extracting day from Dat29eTime in df_lowercase to match with Date in df_uppercase
df_lowercase_with_date = df_lowercase.withColumn("Date", F.dayofmonth("DateTime"))

"""pulls out the day number from date-time column, and creates a brand-new column called "Date"
"""

#Perform an Inner Join on the 'Date' column
joined_df = df_lowercase_with_date.join(df_uppercase, on="Date", how="inner") \
    .select("Date", "Junction", "Vehicles", "Traffic Situation", "Total")

print("Sample Joined Records:")
joined_df.show(5)

"""performing an inner join on the "Date" column to combine the two datasets, matching the hourly vehicle counts from the sensor logs with the overall traffic situation labels for those same days.

#Q5 Exploratory Data Analysis and Spark SQL
"""

# Register DataFrames as temporary SQL views
df_lowercase.createOrReplaceTempView("traffic_lowercase")
df_uppercase.createOrReplaceTempView("traffic_uppercase")

"""1. Identify Peak Traffic Hour"""

# Using traffic_lowercase to extract hour from DateTime
peak_hours = spark.sql("""
    SELECT HOUR(DateTime) AS Hour, SUM(Vehicles) AS Total_Vehicles
    FROM traffic_lowercase
    GROUP BY Hour
    ORDER BY Total_Vehicles DESC
""")
peak_hours.show(5)

"""finding the most heavily congested hours of the day using an SQL query."""

# Convert to Pandas for plotting
pdf_peak = peak_hours.toPandas()

plt.figure(figsize=(10, 6))
sns.barplot(data=pdf_peak, x="Hour", y="Total_Vehicles", palette="viridis")
plt.title("Peak Traffic Hours")
plt.xlabel("Hour of Day")
plt.ylabel("Total Vehicles")
plt.show()

"""Traffic volume follow a clear bimodal distribution throughout the day, showing a minor peak during midday (Hour 12) and a massive spike during the evening commute, with congestion explicitly peaking between 7:00 PM and 8:00 PM (Hours 19 and 20). This indicates that evening rush hour represents the highest bottleneck period for vehicle volume across the monitored junctions.

2. Analyze Route-Wise Traffic Density
"""

# Using Junction as a proxy for routes/locations
route_density = spark.sql("""
    SELECT Junction, AVG(Vehicles) AS Avg_Vehicles, MAX(Vehicles) AS Max_Vehicles
    FROM traffic_lowercase
    GROUP BY Junction
    ORDER BY Avg_Vehicles DESC
""")
route_density.show()

"""calculating route-wise traffic density using an SQL query."""

pdf = route_density.toPandas()
pdf_melted = pdf.melt(id_vars=["Junction"], value_vars=["Avg_Vehicles", "Max_Vehicles"], var_name="Metric", value_name="Vehicle_Count")

plt.figure(figsize=(10, 6))
sns.barplot(data=pdf_melted, x="Junction", y="Vehicle_Count", hue="Metric", palette="muted")

plt.title("Route-Wise Traffic Density (Average vs Max Vehicles)")
plt.xlabel("Junction")
plt.ylabel("Number of Vehicles")
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""While Junction 1 carries the highest constant traffic volume with the largest daily baseline (Avg_Vehicles), Junction 3 is highly unpredictable and experiences the most extreme bottleneck, reaching the single highest traffic spike (Max_Vehicles = 180) across all monitored locations.

3. Determine Average Travel Time / Traffic Volume by Location
"""

# Analyzing vehicle components across different registered situations/days
location_stats = spark.sql("""
    SELECT `Day of the week`, `Traffic Situation`, AVG(Total) AS Avg_Total_Vehicles
    FROM traffic_uppercase
    GROUP BY `Day of the week`, `Traffic Situation`
    ORDER BY Avg_Total_Vehicles DESC
""")
location_stats.show(5)

"""calculating the average total number of vehicles across different traffic situations and days of the week"""

pdf_density = route_density.toPandas()

plt.figure(figsize=(8, 5))
sns.barplot(data=pdf_density, x="Junction", y="Avg_Vehicles", color="salmon")
plt.title("Average Traffic Density by Junction")
plt.show()

"""Junction 1 serves as the absolute primary traffic hotspot, experiencing a significantly higher average vehicle density than all other monitored locations combined. Meanwhile, Junction 4 remains the clearest route with the lowest average traffic density, while Junctions 2 and 3 exhibit nearly identical, moderate traffic patterns.

4. Identify Congestion Hotspots
"""

# Finding situations where traffic is explicitly marked as heavy or high volume
hotspots = spark.sql("""
    SELECT Date, `Day of the week`, Time, Total, `Traffic Situation`
    FROM traffic_uppercase
    WHERE `Traffic Situation` IN ('heavy', 'high')
    ORDER BY Total DESC
""")
hotspots.show(5)

"""filtering the data to isolate extreme traffic congestion hotspots"""

# Assuming you aggregate counts by situation
pdf_situations = aggregated_rdd.toDF(["Situation", "Count"]).toPandas()

plt.figure(figsize=(8, 6))
plt.pie(pdf_situations["Count"], labels=pdf_situations["Situation"], autopct='%1.1f%%')
plt.title("Distribution of Traffic Situations")
plt.show()

"""The overwhelming majority of tracked traffic falls under the "normal" and "heavy" classifications, which combined make up the bulk of the chart. In contrast, "low" traffic conditions occur least frequently, indicating that the monitored routes experience a sustained baseline of moderate-to-severe vehicle volume rather than free-flowing conditions

5. Generate Daily and Monthly Traffic Trend Reports
"""

# Extracting monthly and daily trends from the timestamp data
trends = spark.sql("""
    SELECT
        MONTH(DateTime) AS Month,
        DAY(DateTime) AS Day,
        SUM(Vehicles) AS Total_Vehicles
    FROM traffic_lowercase
    GROUP BY Month, Day
    ORDER BY Month, Day
""")
trends.show(5)

"""extracting daily and monthly traffic trends"""

pdf_trends = trends.toPandas()

plt.figure(figsize=(12, 6))
sns.lineplot(data=pdf_trends, x="Day", y="Total_Vehicles", hue="Month", marker='o')
plt.title("Daily Traffic Trends by Month")
plt.show()

"""The line chart reveals distinct seasonality and a clear upward trajectory in traffic volume as the year progresses. Monthly vehicle counts start at their lowest baseline during the winter (Months 1 and 2) and steadily scale upward, reaching peak baseline volumes during the late autumn and early winter months (Months 10 and 12). Additionally, regardless of the month, traffic exhibits a highly volatile but rhythmic cyclical pattern across the days of the month, indicating repeating weekly patterns of weekend drops and weekday rushes.

#Q6. ETL Pipeline Development
"""

from pyspark.sql import functions as F

def run_traffic_etl_pipeline():
    #1. EXTRACT--Loading Raw Data
    # Extract data from the sources(reading the 2 csv files)
    df_sensor_logs = spark.read.csv("1traffic.csv", header=True, inferSchema=True)
    df_situation_reports = spark.read.csv("Traffic.csv", header=True, inferSchema=True)

    #2. TRANSFORM--Cleaning and Joining Datasets
    # Step A: Standardize lowercase dataset by extracting the Date matching key
    #extracting the Date and Hour from the timestamp,
    df_sensors_processed = df_sensor_logs.withColumn("Date", F.dayofmonth("DateTime")).withColumn("Hour", F.hour("DateTime"))

    # Step B: Filter out records with invalid or missing traffic counts
    #filtering out the invalid rows
    df_situations_cleaned = df_situation_reports.filter(df_situation_reports["Total"] > 0)

    # Step C: Combine datasets using an Inner Join on the common 'Date' column
    #merging the hourly counts with the traffic situation labels
    centralized_analytics_df = df_sensors_processed.join(
        df_situations_cleaned,
        on="Date",
        how="inner"
    ).select(
        "Date",
        "Hour",
        "Junction",
        "Vehicles",
        "CarCount",
        "BikeCount",
        "Total",
        "Traffic Situation"
    )

    #3. LOAD--Writing into Centralized Repository
    # Load the transformed data into a centralized Parquet repository (partitioned by Date)
    centralized_analytics_df.write.mode("overwrite").partitionBy("Date").parquet("centralized_traffic_repository")

    print("ETL Pipeline Execution Completed Successfully!")

# Run the pipeline
run_traffic_etl_pipeline()

"""Apache Parquet is a highly optimized, open-source columnar storage file format designed specifically for big data processing in systems like Apache Spark, Hadoop, and AWS Athena.

#Q7. Machine Learning/Deep Learning Implementation
"""

from pyspark.ml.feature import VectorAssembler, StringIndexer
from pyspark.ml.regression import RandomForestRegressor
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.ml.regression import LinearRegression
from pyspark.ml.regression import DecisionTreeRegressor

"""**RANDOM FOREST REGRESSOR**

1. Feature Engineering
"""

# Convert the categorical "Traffic Situation" string column into numerical indices
indexer = StringIndexer(inputCol="Traffic Situation", outputCol="Traffic_Situation_Index")
df_indexed = indexer.fit(df_uppercase).transform(df_uppercase)

"""converting the categorical column Traffic Situation into clean, numerical indices."""

# Assemble feature columns into a single vector column
feature_cols = ["CarCount", "BikeCount", "BusCount", "TruckCount", "Traffic_Situation_Index"]
assembler = VectorAssembler(inputCols=feature_cols, outputCol="features")
data_ml = assembler.transform(df_indexed).select("features", "Total")

# Split the data into training (80%) and testing (20%) sets
train_data, test_data = data_ml.randomSplit([0.8, 0.2], seed=42)

"""2. Model Training"""

# Initialize and train the Random Forest Regressor to predict "Total" vehicles
rf = RandomForestRegressor(featuresCol="features", labelCol="Total", numTrees=20)
rf_model = rf.fit(train_data)

"""3. Model Evaluation"""

# Make predictions on the test dataset
predictions = rf_model.transform(test_data)
predictions.select("Total", "prediction").show(5)

# Evaluate the model's performance using RMSE
evaluator = RegressionEvaluator(labelCol="Total", predictionCol="prediction", metricName="rmse")
rmse = evaluator.evaluate(predictions)

print(f"Root Mean Squared Error (RMSE) on Test Data: {rmse:.4f}")

"""**Decision Tree Regressor**"""

# Initialize and train
dt = DecisionTreeRegressor(featuresCol="features", labelCol="Total")
dt_model = dt.fit(train_data)

# Predict and Evaluate
dt_predictions = dt_model.transform(test_data)
rmse_dt = evaluator.evaluate(dt_predictions)

print(f"Decision Tree RMSE: {rmse_dt:.4f}")

"""Comparison of All Three Models"""

results = {
    "Random Forest": rmse,
    "Decision Tree": rmse_dt
}

print("--- Model Comparison (RMSE) ---")
for model_name, score in results.items():
    print(f"{model_name}: {score:.4f}")

# Finding the best model (lowest RMSE is better)
best_model = min(results, key=results.get)
print(f"\nBest performing model: {best_model}")